### ISSUE TITLE
Script create_ops_users.sh should save to Control Tower folder

### ISSUE THREAD

**Issue by gcharest** [cds-snc/cds-aws-lz#109]
The script currently saves credentials in the Shared SRE folder.

It should save them in Shared SRE\Control Tower folder instead.

**Comment by CalvinRodo** [comment]
Wrong script, creat_awsctexec_role.sh is used to create the AWSControlTowerExecution role, you mean the https://github.com/cds-snc/cds-aws-lz/blob/main/bin/create_ops_users.sh which is used to create roles for new AWS Acconuts

**Comment by gcharest** [comment]
Yes, 100% correct... Need more ☕
