### ISSUE TITLE
Placeholder issue for cost anomaly detection for scratch accounts

### ISSUE THREAD

**Issue by dinophile** [cds-snc/cds-aws-lz#5]
Setup for alerts for unexpected cost changes for our scratch accounts.

Testing between the new detection service vs using a cloudwatch alarm. 

Will link to best fit module once it's decided which way to go.

**Comment by CalvinRodo** [comment]
I don't think we are going to bother with this, we'll just keep an eye on costs through the slack notifier, usage is too all over the place for the ML.
