### ISSUE TITLE
Set an AWS IAM Account Alias during provisioning

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/cds-aws-lz#76]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_account_alias
https://docs.aws.amazon.com/IAM/latest/UserGuide/console_account-alias.html

This will more then likely have to be done through the [aft-account-provisioning-customizations](https://github.com/cds-snc/aft-account-provisioning-customizations) process.

The global customizations and account customizations don't (AFAIK) have access to the Custom Fields.

We might be able global customizations if we base it the alias of the account being generated (account name, or something...) but might not be possible. 

You can see the documentation for AFT here: https://docs.aws.amazon.com/controltower/latest/userguide/aft-architecture.html

Info: 
use a custom field like here: https://github.com/cds-snc/aft-account-request/blob/main/terraform/sretools.tf#L107
Test here in the test-bed account customization: https://github.com/cds-snc/aft-account-customizations/tree/main/testbed
Final work will end up in global customization.
Take a look at OIDC role work that was done, you can just copy the bash script and the terraform that was used for that, it's in the global customization repo. 

You can view the account alias in the accounts IAM page

If you really want to get clever you can look at the code the SME sent to do this all using terraform only instead of bash scripts creating auto.tfvars files. But it's not required. 

```hcl
data "aws_ssm_parameters_by_path" "custom" {
 path = "/aft/account-request/custom-fields/"
}

resource "null_resource" "test_foo" {
  count = contains(data.aws_ssm_parameters_by_path.custom.names, "/aft/account-request/custom-fields/foox") ? 1 : 0

  provisioner "local-exec" {
    command = "echo FOUND;"
  }
}
```

**Comment by gcharest** [comment]
So, according to the [AFT Terraform documentation](https://developer.hashicorp.com/terraform/tutorials/aws/aws-control-tower-aft#account-provisioning-customizations-framework), we'd need to use a Lambda function if we were to trigger this customization at provisioning?

**Comment by gcharest** [comment]
Currently only going to be applied to Scratch so moving to account-customization in the Scratch folder
